SET MODE ORACLE;

CREATE SCHEMA APL_TEST;

CREATE TABLE APL_TEST.TAB_PRODUTOR_RURAL (
    ID VARCHAR(40) NOT NULL,
    INSCRICAO VARCHAR(12) NOT NULL,
    NOME VARCHAR (60) NOT NULL,
    DT_CADASTRO DATE NOT NULL,
    AREA_PROPRIEDADE NUMERIC(3)  NOT NULL
);

CREATE TABLE APL_TEST.TAB_PRODUTO (
    ID VARCHAR(40) NOT NULL,
    NOME VARCHAR(10)
);

CREATE TABLE APL_TEST.TAB_PRODUCAO (
    ID VARCHAR(40) NOT NULL,
    ID_PRODUTOR_RURAL VARCHAR(40) NOT NULL,
    ID_PRODUTO VARCHAR(40) NOT NULL,
    QUANTIDADE NUMERIC(5) NOT NULL,
    DT_CADASTRO DATE NOT NULL
);
